#!/usr/bin/env python3
"""Append a run entry to a book project's audit log.

Shared by every book-machine skill so each run leaves a trail: which skill ran, when,
whether it passed or failed (or its verdict), the items it ran through, and the outputs
it wrote. Writes a human-readable `audit-log.md` and a machine-readable `audit-log.jsonl`
in the target folder (the book project folder).

Usage:
    python audit_log.py --skill style-check --target ./my-book --status PASS \
        --item 01-foo.md --item 02-bar.md --output style-report.md --note "2 chapters scanned"

  --skill   (required) the skill that ran
  --target  folder the log lives in (default: current dir)
  --status  PASS | FAIL | DONE | GO | HOLD | READY | NOT-READY | … (default DONE)
  --item    one item processed; repeatable. Or --items "a, b, c"
  --output  one file written; repeatable. Or --outputs "x, y"
  --note    one-line summary
  --by      who/what ran it (default: book-machine)

Standard library only.
"""

import argparse
import json
import os
import sys
from datetime import datetime

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass


def split_csv(values):
    out = []
    for v in values or []:
        out.extend(p.strip() for p in v.split(",") if p.strip())
    return out


def main():
    ap = argparse.ArgumentParser(description="Append a run entry to the audit log.")
    ap.add_argument("--skill", required=True)
    ap.add_argument("--target", default=".")
    ap.add_argument("--status", default="DONE")
    ap.add_argument("--item", action="append", default=[])
    ap.add_argument("--items", action="append", default=[])
    ap.add_argument("--output", action="append", default=[])
    ap.add_argument("--outputs", action="append", default=[])
    ap.add_argument("--note", default="")
    ap.add_argument("--by", default="book-machine")
    args = ap.parse_args()

    target = os.path.abspath(args.target)
    if os.path.isfile(target):
        target = os.path.dirname(target)
    if not os.path.isdir(target):
        print(f"error: target folder does not exist: {target}", file=sys.stderr)
        return 2

    items = (args.item or []) + split_csv(args.items)
    outputs = (args.output or []) + split_csv(args.outputs)
    status = args.status.strip().upper()
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # human-readable markdown
    md_path = os.path.join(target, "audit-log.md")
    new = not os.path.exists(md_path)
    lines = []
    if new:
        lines.append(f"# Audit log — {os.path.basename(target)}\n")
        lines.append("One entry per skill run, oldest first. Generated by the book-machine "
                     "skills via `lib/audit_log.py`.\n")
    lines.append(f"\n## {args.skill} — {ts} · {status}")
    lines.append(f"- Ran: yes ({args.by})")
    lines.append(f"- Result: {status}")
    if items:
        shown = ", ".join(items[:40]) + (" …" if len(items) > 40 else "")
        lines.append(f"- Items ({len(items)}): {shown}")
    else:
        lines.append("- Items: (none recorded)")
    lines.append(f"- Outputs: {', '.join(outputs) if outputs else 'none (read-only)'}")
    if args.note:
        lines.append(f"- Note: {args.note}")
    with open(md_path, "a", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    # machine-readable jsonl
    rec = {"ts": ts, "skill": args.skill, "status": status, "by": args.by,
           "items": items, "outputs": outputs, "note": args.note}
    with open(os.path.join(target, "audit-log.jsonl"), "a", encoding="utf-8") as f:
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    print(f"audit-log: recorded {args.skill} [{status}] "
          f"({len(items)} item(s), {len(outputs)} output(s)) -> {md_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
